const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ui={score:document.querySelector('#score'),uptime:document.querySelector('#uptime'),level:document.querySelector('#level'),best:document.querySelector('#best'),overlay:document.querySelector('#overlay'),start:document.querySelector('#start')};
let state,raf,last=0,best=+(localStorage.systemsRunnerBest||0);ui.best.textContent=String(best).padStart(5,'0');
const ground=292,player={x:105,y:ground-46,w:34,h:46,vy:0};
function reset(){state={running:true,score:0,uptime:100,speed:330,next:1,objects:[],particles:[],boost:0};player.y=ground-player.h;player.vy=0;last=performance.now();ui.overlay.classList.add('hidden');raf=requestAnimationFrame(loop)}
function jump(){if(!state?.running){reset();return}if(player.y>=ground-player.h-2){player.vy=-610;burst(player.x+15,ground,'#70e1c1',7)}}
function spawn(){const ai=Math.random()<.2;const outage=!ai&&Math.random()<.35;state.objects.push({x:canvas.width+30,y:ai?ground-88:ground-(outage?55:34),w:ai?26:outage?32:22,h:ai?26:outage?55:34,type:ai?'ai':outage?'outage':'latency',taken:false});state.next=.75+Math.random()*1.25}
function burst(x,y,color,count){for(let i=0;i<count;i++)state.particles.push({x,y,vx:(Math.random()-.5)*180,vy:-Math.random()*180,life:1,color})}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function end(){state.running=false;cancelAnimationFrame(raf);best=Math.max(best,Math.floor(state.score));localStorage.systemsRunnerBest=best;ui.best.textContent=String(best).padStart(5,'0');ui.overlay.querySelector('h2').textContent='REQUEST DROPPED';ui.overlay.querySelector('p').innerHTML=`Score ${Math.floor(state.score)} · Press <kbd>Space</kbd> to redeploy`;ui.start.textContent='Redeploy';ui.overlay.classList.remove('hidden')}
function update(dt){state.score+=dt*(12+state.boost*15);state.speed=Math.min(650,330+state.score*.12);state.next-=dt;if(state.next<=0)spawn();state.boost=Math.max(0,state.boost-dt);player.vy+=1550*dt;player.y=Math.min(ground-player.h,player.y+player.vy*dt);for(const o of state.objects){o.x-=state.speed*dt;if(hit(player,o)&&!o.taken){if(o.type==='ai'){o.taken=true;state.boost=3;state.score+=100;burst(o.x,o.y,'#b77aff',16)}else{state.uptime=Math.max(0,state.uptime-(o.type==='outage'?55:34)*dt*7);burst(player.x+30,player.y+25,o.type==='outage'?'#fa709a':'#e9b949',2)}}}state.objects=state.objects.filter(o=>o.x>-80&&!o.taken);for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=350*dt;p.life-=dt}state.particles=state.particles.filter(p=>p.life>0);if(state.uptime<=0)end();ui.score.textContent=String(Math.floor(state.score)).padStart(5,'0');ui.uptime.textContent=`${state.uptime.toFixed(2)}%`;ui.level.textContent=String(1+Math.floor(state.score/500))}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#0d1422';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#1d2b46';ctx.lineWidth=1;for(let x=0;x<canvas.width;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,ground);ctx.stroke()}ctx.strokeStyle='#2c4168';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,ground);ctx.lineTo(canvas.width,ground);ctx.stroke();for(let x=-(state?.score||0)*8%80;x<canvas.width;x+=80){ctx.fillStyle='#172440';ctx.fillRect(x,ground+18,48,5)}
  ctx.save();ctx.translate(player.x,player.y);ctx.fillStyle=state?.boost?'#b77aff':'#70e1c1';ctx.fillRect(4,5,26,25);ctx.fillStyle='#0d1422';ctx.fillRect(20,11,5,5);ctx.fillStyle='#7aa2ff';ctx.fillRect(0,32,12,14);ctx.fillRect(22,32,12,14);ctx.restore();
  for(const o of state?.objects||[]){ctx.fillStyle=o.type==='ai'?'#b77aff':o.type==='outage'?'#fa709a':'#e9b949';if(o.type==='ai'){ctx.beginPath();ctx.arc(o.x+13,o.y+13,13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 12px monospace';ctx.fillText('AI',o.x+5,o.y+17)}else{ctx.fillRect(o.x,o.y,o.w,o.h);ctx.fillStyle='#0d1422';ctx.font='bold 18px monospace';ctx.fillText(o.type==='outage'?'!':'⌁',o.x+7,o.y+23)}}for(const p of state?.particles||[]){ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,4,4)}ctx.globalAlpha=1;ctx.fillStyle='#60749b';ctx.font='12px monospace';ctx.fillText(state?.boost?'AI ASSIST // ACTIVE':'REQUEST // IN FLIGHT',22,28)}
function loop(now){const dt=Math.min(.032,(now-last)/1000);last=now;if(state.running){update(dt);draw();raf=requestAnimationFrame(loop)}}
addEventListener('keydown',e=>{if(['Space','ArrowUp','KeyW'].includes(e.code)){e.preventDefault();jump()}});canvas.addEventListener('pointerdown',jump);ui.start.addEventListener('click',reset);draw();
